CREATE TABLE USER(
	UID INTEGER PRIMARY KEY, --AUTO INC
	USERNAME TEXT NOT NULL UNIQUE,
    PASSWD TEXT NOT NULL,
    NAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL UNIQUE,
    PHONE TEXT NOT NULL UNIQUE,
    ADDRESS TEXT NOT NULL
);

-- Permission 0: public, 1: private

CREATE TABLE FILE(
	FILEID INTEGER PRIMARY KEY,    --AUTO INC
    FILENAME TEXT NOT NULL,
    FPERMISSION BOOLEAN NOT NULL DEFAULT 0,
    SIZE REAL NOT NULL DEFAULT 0.0,
    UID INTEGER,
    P_FOLDERID INTEGER NOT NULL,
    FOREIGN KEY(UID) REFERENCES USER(UID),
    FOREIGN KEY(P_FOLDERID) REFERENCES FOLDER(FOLDERID)
);

CREATE TABLE FOLDER(
	FOLDERID INTEGER PRIMARY KEY,  --AUTO INC
    FOLDERNAME TEXT NOT NULL,
    UID INTEGER,
    P_FOLDERID INTEGER,
    FOREIGN KEY(UID) REFERENCES USER(UID),
    FOREIGN KEY(P_FOLDERID) REFERENCES FOLDER(FOLDERID)
);