
DROP TABLE FILE;
DROP TABLE FOLDER;
DROP TABLE USER;

CREATE TABLE USER(
	UID INTEGER PRIMARY KEY, --AUTO INC
	USERNAME TEXT NOT NULL UNIQUE,
    PASSWD TEXT NOT NULL,
    NAME TEXT NOT NULL,
    EMAIL TEXT,
    PHONE TEXT
);
INSERT INTO USER (UID,USERNAME,PASSWD,NAME,EMAIL,PHONE) VALUES (1,'user1','pass1','Chitta','chitta@gmail.com','234567896'),
 (2,'user2','pass2','Prakash','pnj@outlook.com','98765434335');

CREATE TABLE FOLDER(
	FOLDERID INTEGER PRIMARY KEY,  --AUTO INC
    FOLDERNAME TEXT NOT NULL,
    UID INTEGER,
    P_FOLDERID INTEGER,
    FOREIGN KEY(UID) REFERENCES USER(UID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(P_FOLDERID) REFERENCES FOLDER(FOLDERID) ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO FOLDER (FOLDERID,FOLDERNAME,UID,P_FOLDERID) VALUES (1,'user1_home',1,NULL),
 (2,'user2_home',2,NULL),
 (3,'dir1',1,1),
 (4,'dir1',2,2);


CREATE TABLE FILE(
	FILEID INTEGER PRIMARY KEY,    --AUTO INC
    FILENAME TEXT NOT NULL,
    FPERMISSION BOOLEAN NOT NULL DEFAULT 0,
    SIZE REAL NOT NULL DEFAULT 0.0,
    UID INTEGER,
    P_FOLDERID INTEGER NOT NULL,
    FOREIGN KEY(UID) REFERENCES USER(UID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(P_FOLDERID) REFERENCES FOLDER(FOLDERID) ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO FILE (FILEID,FILENAME,FPERMISSION,SIZE,UID,P_FOLDERID) VALUES (1,'AssignmentReport.txt',0,5438.0,1,1),
 (2,'Id.jpg',0,23.0,1,3),
 (3,'EPFO_Claim.pdf',1,132.0,1,1),
 (4,'HackingClubIntro.txt',0,12.0,2,2);
COMMIT;
